Avoid granting Linux capabilities
microservices-demo/payment pull request #40
Opened 2020-09-01 16:39 UTC by shiresky

My task was to run your Helm chart on K8s cluster with restrictive pod security policy. The worst problem I encountered was that you grant Linux capabilities in order to bind 80 port inside of container. As a result I was not able to run these images in any way without rebuilding them reverting this operation. That's why I propose you to use other port inside of containers and map it externally to 80 during running a container.

2020-10-16 15:07 UTC, CsatariGergely commented
@Ottovsky can you please review this?

2020-10-19 15:19 UTC, Ottovsky commented
> @Ottovsky can you please review this?
Sure, will do it later this week. Can you rebase this PR onto upstream master?

2020-10-20 12:15 UTC, Ottovsky requested changes
Please rebase onto upstream master, rest of the changes are ok.

2020-10-21 08:44 UTC, Ottovsky approved these changes

2020-10-21 08:44 UTC, merged

2020-10-21 08:45 UTC, Ottovsky commented
Merged, thank you for the contribution!